### ISSUE TITLE
Unable to create sitemap using console command

### ISSUE THREAD

**Issue by deadmantfa** [assayer-pro/yii2-sitemap-module#9]
Hi Assayer-pro,
I followed your documentation but got into a hassle
I have set the behavior in my model as such
`
'sitemap' => [
                'class' => '\assayerpro\sitemap\behaviors\SitemapBehavior',
                'scope' => function ($model) {
                    /** @var \yii\db\ActiveQuery $model */
                    $model->select(['username', 'update_at']);
                    $model->andWhere(['status' => 2]);
                },
                'dataClosure' => function ($model) {
                    /** @var self $model */
                    return [
                        'loc' => Url::to(urlencode($model->username), true),
                        'lastmod' => strtotime($model->update_at),
                        'changefreq' => \assayerpro\sitemap\Sitemap::DAILY,
                        'priority' => 0.8
                    ];
                }
            ],
`
And my console config looks like this
`
'sitemap' => [
            'class' => 'assayerpro\sitemap\Sitemap',
            'models' => [
                'common\models\User'
            ],
]
`

the error I am getting is
PHP Warning 'yii\base\ErrorException' with message 'file_put_contents(/home/deadmantfa/Sites/bbv2/webservice/frontend/web/sitemap/default/index?id=1): failed to open stream: No such file or directory'

in /home/deadmantfa/Sites/bbv2/webservice/vendor/assayer-pro/yii2-sitemap-module/console/CreateController.php:67

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'file_put_conten...', '/home/deadmantf...', 67, Array)
#1 /home/deadmantfa/Sites/bbv2/webservice/vendor/assayer-pro/yii2-sitemap-module/console/CreateController.php(67): file_put_contents('/home/deadmantf...', '<?xml version="...')
#2 [internal function]: assayerpro\sitemap\console\CreateController->actionCreate()
#3 /home/deadmantfa/Sites/bbv2/webservice/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /home/deadmantfa/Sites/bbv2/webservice/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#5 /home/deadmantfa/Sites/bbv2/webservice/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('create', Array)
#6 /home/deadmantfa/Sites/bbv2/webservice/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('create', Array)
#7 /home/deadmantfa/Sites/bbv2/webservice/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('sitemap/create', Array)
#8 /home/deadmantfa/Sites/bbv2/webservice/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('sitemap/create', Array)
#9 /home/deadmantfa/Sites/bbv2/webservice/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#10 /home/deadmantfa/Sites/bbv2/webservice/yii(27): yii\base\Application->run()
#11 {main}

Any help would be great

**Comment by serge-larin** [comment]
Add a new rule for urlManager of your application's configuration file, for example:
```
'urlManager' => [
    'rules' => [
        ['pattern' => 'sitemap-<id:\d+>', 'route' => '/sitemap/default/index', 'suffix' => '.xml'],
        ['pattern' => 'sitemap', 'route' => 'sitemap/default/index', 'suffix' => '.xml'],
    ],
],
```
